export const Endpoints = {
    login: "/",
    createOrganisation: "/create-organisation",
    createAdminUser: "/create-admin",
    units: "/units",
    contracts: "/contracts",
    tennants: "/tennants",
    income: "/income",
    debtors: "/debtors",
    contacts: "/contacts",
    users: "/users",
    unit: "/unit",
    createUnit: "/create-unit",
    editUnit: "/edit-unit",
    contact: "/contact",
    createContact: "/create-contact",
    editContact: "/edit-contact",
    tennant: "/tennant",
    createTennant: "/create-tennant",
    editTennant: "/edit-tennant",
    contract: "/contract",
    createContract: "/create-contract",
    editContract: "/edit-contract",
    user: "/user",
    createUser: "/create-user"
}